### ISSUE TITLE
Trouble on Hetzner Cloud

### ISSUE THREAD

**Issue by dlbone** [stafftastic/jitsu-chart#17]
Hi, once again, thank you for this fantastic helm chart.

I am trying to get this running on a Hetzner cloud instance.

I am able to port forward both the ingest service and the console service separately and they each work appropriately. However I am not able to get access to both of them in the typical unified manner.

Do I need to set up a separate ingress controller that connects to the helm jitsu deployment or is that something that is meant to be managed by the deployment and my issue is the hosting service I'm using?

Thanks for any help.

**Comment by echozio** [comment]
Hi,

The ingress resources the chart creates is meant to work with your existing ingress controller set up separately.

Typically you'll have an ingress controller (such as ingress-nginx) exposed as a LoadBalancer service, and an ingress class associated with it.

If you have an ingress controller set up but it returns a 404 when trying to reach Jitsu it may be due to a missing/invalid ingress class name or the lack of a default ingress class.

With an installation of ingress-nginx using its default values from their Helm chart, the following should be enough to expose Jitsu, given that the domain points to where your ingress controller listens:
```
ingress:
  className: nginx
  host: jitsu.example.com
```

**Comment by echozio** [comment]
Yup, that should do it. The component that provisions load balancers for LoadBalancer services is the CCM. Glad you got it working :100:
